steps:
- name: gcr.io/cloud-builders/docker
  args:
    - "build"
    - "-t"
    - "us.gcr.io/$PROJECT_ID/workspace_sentry-demos-react:$COMMIT_SHA"
    - "-t"
    - "us.gcr.io/$PROJECT_ID/workspace_sentry-demos-react:latest"
    - "-f"
    - "./Dockerfile"
    - "."

images:
- us.gcr.io/$PROJECT_ID/workspace_sentry-demos-react:$COMMIT_SHA
- us.gcr.io/$PROJECT_ID/workspace_sentry-demos-react:latest
